# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:7
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5


        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install flake8 pytest

            - name: Run flake8 lint
              run: |
                  echo "Running flake8..."
                  flake8 src --count --max-complexity=10 --max-line-length=88 --statistics

            - name: Run tests
              env:
                MONGO_URI: "mongodb://localhost:27017/test_db"
                DB_NAME: "test_db"
              run: |
                  echo "Running pytest..."
                  pytest -v --maxfail=3 --disable-warnings
