# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install flake8 pytest

            - name: Run flake8 lint
              run: |
                  echo "Running flake8..."
                  flake8 src --count --max-complexity=10 --max-line-length=88 --statistics

            - name: Run tests
              env:
                  ENV: test
              run: |
                  echo "Running pytest..."
                  pytest -v --maxfail=3 --disable-warnings
